joincalldotco/Call

- packages/ui/src/components/button.tsx
Updated the file import 
- importing file `import { cn } from "@call/ui/lib/utils"
`
> (fix) : update import path for utility functions in button component

- apps/web/app/api/waitlist/count/route.ts
- apps/web/app/api/waitlist/join/route.ts
- apps/web/package.json
- apps/web/tsconfig.json
- packages/ui/src/components/button.tsx
- pnpm-lock.yaml
This PR adds a new API endpoint `POST /api/waitlist/join` to allow users to sign up for the waitlist.
The endpoint includes:
- Email validation using Zod, restricted to a list of allowed domains.
- IP-based rate limiting (3 requests per 2 minutes) to prevent spam.
- Checks for duplicate email addresses in the database.
---
---
N/A (API endpoint)
---
None.
---
The core logic is within `apps/web/app/api/waitlist/join/route.ts`. Please check the email validation and rate limiting implementation.
> feat: Add waitlist join API endpoint

- apps/web/app/(waitlist)/_components/navbar.tsx
Resolved a hydration mismatch caused by `theme` rendering from `next-themes`. Wrapped the theme toggle logic inside a `useEffect` to ensure it only runs on the client, preventing SSR/CSR inconsistencies.
- Deferred theme-dependent rendering until after component mount
- Ensured consistent rendering between server and client
Hydration error due to mismatch in icon rendering between dark/light mode.
> fix: resolve bug

- apps/web/lib/site.ts
> fix(discord): update expired link to infinite one

- package.json
missing comma ( , ) in `package.json`
---
---
---
---
> Update package.json. Missing comma

- apps/web/lib/site.ts
> fix: update incorrect Twitter URL

- apps/web/app/layout.tsx
- bun.lock
Fixes: #69 (if applicable)
---
---
---
---
> feat: databuddy ad analytics

- README.md
- apps/web/app/(waitlist)/contributors/page.tsx
> style: just for fun

- CODE_OF_CONDUCT.md
Requirement for Vercel Open Source Program
---
---
---
---
> chore(docs): add CODE_OF_CONDUCT.md

- apps/web/app/(app)/r/[id]/page.tsx
- apps/web/components/rooms/room-controls.tsx
in-call ui changes.
---
---
---
---
> style: revamp in-call ui

- apps/web/app/(app)/r/[id]/page.tsx
- apps/web/components/rooms/room-controls.tsx
> feat: i changed the video calling controls color

- packages/auth/src/auth.ts
Follow up fix for https://github.com/joincalldotco/Call/pull/95
> fix: import error

- apps/server/src/routes/calls/index.ts
- apps/web/app/(waitlist)/_components/waitlist.tsx
> fix: waitlist

- apps/server/src/ws-signaling.ts
- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/app/(waitlist)/_components/waitlist.tsx
- apps/web/app/api/waitlist/count/route.ts
- apps/web/app/api/waitlist/join/route.ts
- apps/web/lib/supabase.ts
- apps/web/package.json
- pnpm-lock.yaml
migrate wait list to supabase
Fixes: #100 (if applicable)
---
---
---
---
> feat: migrate waitlist to supabase and something more

- apps/server/src/routes/contacts/index.ts
- packages/auth/package.json
While creating contact, if the user does not exists, it'll send an invite mail to the user.
---
---
---
---
> feat: sending mail invite to non-existing users

- apps/server/src/routes/calls/index.ts
- apps/server/src/ws-signaling.ts
- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/app/(waitlist)/_components/waitlist.tsx
- apps/web/app/api/waitlist/count/route.ts
- apps/web/app/api/waitlist/join/route.ts
- apps/web/lib/supabase.ts
- apps/web/package.json
- pnpm-lock.yaml
fuck neon.com
Fixes: #102 (if applicable)
---
---
---
---
> migrate db to supabase (fuck neon)

- apps/server/src/config/mediasoup.ts
- apps/server/src/index.ts
- apps/server/src/routes/calls/index.ts
- apps/server/src/routes/index.ts
- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/middleware.ts
Fix: The mediasoup worker was added
Fixes: #103 (if applicable)
---
---
---
---
> fix(generate-binary): mediasoup worker

- apps/server/src/mediasoup-server.ts
- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/hooks/useMediasoupClient.ts
- apps/web/hooks/useSocket.ts
fixed some issues.
Fixes: #108(if applicable)
---
---
---
---
> Mediasoup worker

- apps/web/components/app/section/notification-section.tsx
Fixes: #114 (if applicable)
---
---
---
---
> fix: changed the invitation path from /call/:id to app/call/:id

- apps/server/src/routes/calls/index.ts
- apps/web/components/app/section/notification-section.tsx
- apps/web/components/app/section/team-section.tsx
Now you can join a call with your team directly and send them notifications instantly.
Fixes: #121 (if applicable)
---
---
---
---
> feat: join the call directly with the team and send them notifications

- apps/web/app/(app)/app/layout.tsx
- apps/web/components/app/section/_components/call-history.tsx
- apps/web/components/app/section/call-section.tsx
- package.json
- packages/ui/src/components/avatar.tsx
- pnpm-lock.yaml
Temporary deactivation of the scheduling section
Fixes: #125 (if applicable)
---
---
---
---
> feat: temporary deactivation of the scheduling section

- apps/server/src/routes/calls/index.ts
- apps/web/components/app/section/_components/call-history.tsx
pfp on history card 
Fixes: #137(if applicable)
---
---
---
---
> feat: pfp on card history

- apps/web/app/(app)/layout.tsx
- apps/web/components/app/section/_components/create-team-modal.tsx
- apps/web/components/app/section/team-section.tsx
- packages/auth/src/auth-client.ts
- packages/auth/src/auth.ts
Reverts joincalldotco/Call#156
> Revert "Fix/redirection issues"

- PRODUCTION_SETUP.md
- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/app/(app)/app/profile/page.tsx
- apps/web/components/app/section/_components/create-call-modal.tsx
- apps/web/components/app/section/_components/modal-contact.tsx
- apps/web/components/app/section/_components/team-switcher.tsx
- apps/web/components/app/section/contacts-list.tsx
- apps/web/components/app/section/notification-section.tsx
- apps/web/components/rooms/participants-sidebar.tsx
- apps/web/lib/api-client.tsx
- apps/web/lib/create-request.ts
> chore(env): some changin on .env imports

- apps/server/package.json
- apps/server/src/index.ts
- apps/web/hooks/useSocket.ts
> feat: separate mediasoup and index.js

- apps/server/src/mediasoup-server.ts
- apps/web/hooks/useSocket.ts
Reverts joincalldotco/Call#171
> Revert "feat: na"

- apps/server/package.json
- apps/server/src/mediasoup-server.ts
- pnpm-lock.yaml
>.env on server was added 
Fixes: #175 (if applicable)
---
---
---
---
> chore: access to .env from server

- apps/web/components/modal/contact-selector.tsx
- apps/web/components/modal/start-call.tsx
add invite contacto to call 
Fixes: #177(if applicable)
---
---
---
---
> feat: add invite contact to call

- ERRORS.md
- README.md
- setup_dev_windows.sh
This PR adds a Windows-specific setup script (`setup_dev_windows.sh`) to help developers get started on Windows environments with minimal friction. It also updates the relevant documentation to reference the new script.
**Fixes:** N/A (Windows compatibility improvement)
---
---
_No UI changes introduced._
---
N/A
---
- The new script is named `setup_dev_windows.sh` and located at the root of the project.
- It installs dependencies and prepares the environment for Windows users.
- Documentation (README or developer setup guide) has been updated to include instructions for running the script.
> fix: windows script

- apps/web/hooks/use-call-join.ts
new og 
Fixes: #212 (if applicable)
---
---
---
---
> feat: new og

- apps/web/components/app/section/_components/nav-main.tsx
just fixing start call button 
Fixes: #222 (if applicable)
---
---
---
---
> feat: fixing start call sidebar button

- apps/web/components/auth/social-button.tsx
fixing better auth error 
Fixes: #223 (if applicable)
---
---
---
---
> fix: better auth error #1

- apps/web/app/(waitlist)/_components/navbar.tsx
- apps/web/components/providers/theme-and-query.tsx
- apps/web/components/shared/logo.tsx
remove light mod for now 
Fixes: #231 (if applicable)
---
---
---
---
> style(ui): remove light mood

- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/components/call/media-controls.tsx
- apps/web/components/rooms/chat-sidebar.tsx
- apps/web/components/rooms/participants-sidebar.tsx
- apps/web/contexts/call-context.tsx
- packages/ui/src/components/icons.tsx
got message icon on call
Fixes: #256(if applicable)
---
---
---
---
> style(ux): got message icon

- apps/web/app/(app)/app/call/[id]/page.tsx
- apps/web/app/exp/page.tsx
- apps/web/components/call/call-video-grid.tsx
- apps/web/next.config.mjs
- packages/auth/src/auth.ts
Reverts joincalldotco/Call#263
> Revert "feat: added the grid and modified the experiment"

- apps/web/app/(waitlist)/roadmap/page.tsx
- apps/web/components/app/section/_components/call-history.tsx
- apps/web/components/app/section/contacts-list.tsx
load hidding the call 
Fixes: #266 (if applicable)
---
---
---
---
> feat: load hidding the call on history
